//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymProcess.Models
{
    using System;
    
    public partial class SP_GETUSERBYID_Result2
    {
        public string UserName { get; set; }
        public string Email { get; set; }
        public string MemberName { get; set; }
        public string Mobile { get; set; }
    }
}
