//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymProcess.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tbl_Member
    {
        public int MemberId { get; set; }
        [Required]
        [StringLength(160)]
        public string MemberName { get; set; }
        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Phone Number")]
        [Required(ErrorMessage = "Phone Number Required!")]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$",
                   ErrorMessage = "Entered phone format is not valid.")]
        public string Mobile { get; set; }
        [RegularExpression(@"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}",
 ErrorMessage = "Email doesn't look like a valid email address.")]
        public string Email { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Addess { get; set; }
        public string Sex { get; set; }
        public decimal Weight { get; set; }
        public decimal Height { get; set; }
        public string BloodGroup { get; set; }
        public string MemberType { get; set; }
        public Nullable<decimal> PaymentDetail { get; set; }
        public Nullable<System.DateTime> IsCreated { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string ImageURL { get; set; }
        public string RoleId { get; set; }
        public Nullable<int> SchemeId { get; set; }
        public string AspUserId { get; set; }
    
        public virtual AspNetRole AspNetRole { get; set; }
        public virtual Scheme Scheme { get; set; }
    }
}
